### ISSUE TITLE
Training Loop Code

### ISSUE THREAD

**Issue by brianjsl** [qianmingduowan/AIM2020-bokeh-BGNet#1]
Hello,

Could you also post the code for the training loop? It would be really helpful.

**Comment by qianmingduowan** [comment]
Hi Brian, 
I have sent you an email. You can reply to me in an email.
I will not publicize the training code in a  short time because I haven't done related work in a long time.
You can get my rough code by email.
It's not difficult to reproduce our code for we did it in an end-to-end way.
